AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/MethodName:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 12

Naming/VariableNumber:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Max: 16
  Exclude:
    - "test/**/*"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Style/OneClassPerFile:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"

Style/NumericLiterals:
  Exclude:
    - "test/**/*"
